### PR TITLE
Add EditorConfig file 

### PR DESCRIPTION
**Pull request by paramt**
I think we should have an `.editorconfig` file so we can maintain a consistent code style. I've started with a basic configuration, but feel free to suggest any changes...

[What is EditorConfig?](https://editorconfig.org/)

### CODE REVIEW

**Comment by loucadufault** [comment]
great idea!
quick question what's the motivation behind applying to every file? are we confident that's safe?

**Comment by paramt** [comment]
Good point, I changed it so now it just applies to python files

**Comment by loucadufault** [comment]
I think anyways we'll only have python files and training files, so there would be no difference. But just in case this might be safer. 
thanks and ill merge right now

**Comment by loucadufault** [comment]
ill leave this open for now just so i can merge it into master

**Pull request merged**
